spring:
  profiles:
    active: dev

#dev ayarları
---
spring:
  profiles: dev
  application:
    name: microlearning
  datasource:
    url:  jdbc:postgresql://52.15.236.131:5432/microlearning
    username: power_user
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 80

log:
  file:
    path: ${user.home}/logs/${spring.application.name}

#prod ayarları
---

spring:
  profiles: prod
  application:
    name: microlearning
  datasource:
    url:  jdbc:postgresql://52.15.236.131:5432/microlearning
    username: power_user
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 80

log:
  file:
    path: ${user.home}/logs/${spring.application.name}